### PR TITLE
Draft: Use default hasher

### PR DESCRIPTION
**Pull request by as6520**
Use default hasher rather than xxhash

### CODE REVIEW

**Comment by cfunk1210** [comment]
The reason for this is Jon had mentioned that xxhash was much more secure/better than the default one.  Not sure if it matters much.  This looks like a fine change though.

**Comment by as6520** [comment]
Talked to jon about it and it looks like using the default hasher is the safest solution to sort out the problem of xxhash not being detected

**Comment by cfunk1210** [comment]
Ok, then this is fine.

**Review by cfunk1210 — APPROVED** [review]
LGTM

**Pull request merged**
